### ISSUE TITLE
regex error

### ISSUE THREAD

**Issue by FabriceLuo** [FabriceLuo/butterfly#3]
https://github.com/luominghao/butterfly/blob/8a166a5fac5ec725085a785fa5c062d50276b2f3/shell/autossh/autossh.sh#L33
the right:"(\w+@)?[0-2]?[0-9]{0,2}(\.[0-2]?[0-9]{0,2}){3}"

**Comment by luominghao** [comment]
fix on 2512e770cf63267a516a9f927090d799b54b5168 commit

**Comment by FabriceLuo** [comment]
fixed on 2512e770cf63267a516a9f927090d799b54b5168 commit
